version: '3.5'
services:
  rmqnamesrv:
    image: foxiswho/rocketmq:server
    container_name: rmqnamesrv
    ports:
      - ${port.appDepend.rocketmq.rmqnamesrv}:9876
    volumes:
      - /mnt/data_disk/docker-volume/project/project-name/rocketmq/rmqnamesrv/logs:/opt/logs
      - /mnt/data_disk/docker-volume/project/project-name/rocketmq/rmqnamesrv/store:/opt/store
    networks:
        rmq:
          aliases:
            - rmqnamesrv

  rmqbroker:
    image: foxiswho/rocketmq:broker
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /mnt/data_disk/docker-volume/project/project-name/rocketmq/rmqbroker/log:/opt/logs
      - /mnt/data_disk/docker-volume/project/project-name/rocketmq/rmqbroker/store:/opt/store
      - /mnt/data_disk/docker-volume/project/project-name/rocketmq/rmqbroker/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
        NAMESRV_ADDR: "rmqnamesrv:9876"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8080:${port.appDepend.rocketmq.rmqconsole}
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole
networks:
  rmq:
    name: rmq
    driver: bridge
