server:
  port: 9090

#rocketmq配置
rocketmq:
  name-server: 192.168.190.28:39876
  # 生产者配置
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    maxMessageSize: 4096
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    group: test
  # 消费者配置
  consumer:
    group: test
spring:
  profiles:
    active: mq
  main:
    allow-bean-definition-overriding: true
