server:
  port: 9090

# 日志配置
logging:
  level:
    # 注意注意注意 一定要修改成自己的包名
    # 如果你只需要输出info，可以不用修改成自己的包名，但是如果为其他级别，
    # 比如debug必修改成自己的包名才会生效
    com.projectstart: debug
  file:
    path: /mnt/logs/projectstart-news

#rocketmq配置
rocketmq:
  name-server: 192.168.190.28:39876
  # 生产者配置
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    maxMessageSize: 4096
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    group: test
  # 消费者配置
  consumer:
    group: test
spring:
  profiles:
    active: mq
  main:
    allow-bean-definition-overriding: true
